name = "Blue Theme"
description = "A classic blog theme"
license = "MIT"
homepage = "https://github.com/getzola/hyde"
# The minimum version of Zola required
min_version = "0.4.0"
# An optional live demo URL
demo = ""

# The default language; used in feeds and search index
default_language = "en"

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

[search]
include_title = true
include_description = false
include_content = true

# Any variable there can be overridden in the end user `config.toml`
# You don't need to prefix variables by the theme name but as this will
# be merged with user data, some kind of prefix or nesting is preferable
# Use snake_casing to be consistent with the rest of Zola
[extra]

# The place where the logo in the navbar should link to
logo_redirect_to = "/docs/"

# If you enable this option, a select widget will be available to switch between different versions.
# You need to provide an url for a jsonp file, an example can be found in the bluetheme docs.
# version_choices = "http://br-www-docs.s3-website-us-east-1.amazonaws.com/data.jsonp"

[extra.sponsor]
name = "Blue Robotics"
url = "https://bluerobotics.com"

[[extra.license]]
name = "GPLv3"
url = "https://www.gnu.org/licenses/gpl-3.0.en.html#license-text"

[[extra.license]]
name = "MIT"
url = "https://opensource.org/license/mit"
